// <auto-generated />
using System;
using Howestprime.Movies.Infrastructure.Persistence.EntityFramework.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Howestprime.Movies.Infrastructure.Persistence.EntityFramework.Migrations.PostgreSQL
{
    [DbContext(typeof(DomainContextPostgres))]
    [Migration("20250523092845_FixSeederPosters")]
    partial class FixSeederPosters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Howestprime.Movies.Domain.Movie.Movie", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Actors")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AgeRating")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Movies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ebfb9308-6c61-4608-af77-394448808e9b",
                            Actors = "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
                            AgeRating = 16,
                            Description = "A computer hacker learns from mysterious rebels about the true nature of his reality",
                            Duration = 136,
                            Genres = "Sci-fi",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BN2NmN2VhMTQtMDNiOS00NDlhLTliMjgtODE2ZTY0ODQyNDRhXkEyXkFqcGc@._V1_.jpg",
                            Title = "The Matrix",
                            Year = 1999
                        },
                        new
                        {
                            Id = "fb258d1a-10a2-4bf9-85cd-ca83585d1ee5",
                            Actors = "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
                            AgeRating = 16,
                            Description = "The human city of Zion defends itself against the massive invasion of the machines as Neo fights to end the war at another front while also opposing the rogue Agent Smith.",
                            Duration = 138,
                            Genres = "Sci-fi",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BNjAxYjkxNjktYTU0YS00NjFhLWIyMDEtMzEzMTJjMzRkMzQ1XkEyXkFqcGc@._V1_.jpg",
                            Title = "The Matrix Reloaded",
                            Year = 2003
                        });
                });

            modelBuilder.Entity("Howestprime.Movies.Domain.MovieEvent.Booking", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("BookingStatus")
                        .HasColumnType("integer");

                    b.Property<int>("DiscountVisitors")
                        .HasColumnType("integer");

                    b.Property<string>("MovieEventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("SeatNumbers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StandardVisitors")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MovieEventId");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("Howestprime.Movies.Domain.MovieEvent.MovieEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("MovieId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp(6)");

                    b.Property<int>("Visitors")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieEvents", (string)null);
                });

            modelBuilder.Entity("Howestprime.Movies.Domain.MovieEvent.Room", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Rooms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "f38145ab-9f1e-4778-90f4-b911fb5e15a7",
                            Capacity = 100,
                            Name = "Room 1"
                        },
                        new
                        {
                            Id = "45bfe58a-c9ba-44b6-911e-c1387f6e1ace",
                            Capacity = 200,
                            Name = "Room 2"
                        });
                });

            modelBuilder.Entity("Howestprime.Movies.Domain.MovieEvent.Booking", b =>
                {
                    b.HasOne("Howestprime.Movies.Domain.MovieEvent.MovieEvent", null)
                        .WithMany("Bookings")
                        .HasForeignKey("MovieEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Howestprime.Movies.Domain.MovieEvent.MovieEvent", b =>
                {
                    b.HasOne("Howestprime.Movies.Domain.Movie.Movie", null)
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Howestprime.Movies.Domain.MovieEvent.MovieEvent", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
